# SwiftLint Configuration for OpenChatbot iOS Project
# Reference: https://github.com/realm/SwiftLint

# Paths to include/exclude
included:
  - OpenChatbot/
  - OpenChatbotTests/

excluded:
  - .build/
  - DerivedData/
  - OpenChatbot.xcodeproj/

# Rule Configuration
analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo # Allow TODO comments for development
  - trailing_whitespace # Handled by editor
  - identifier_name # Allow short names like 'id'

# Custom Rules Configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 400
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 5
    error: 10

large_tuple:
  warning: 3
  error: 4

# Naming Rules
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL
    - API

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - url
    - api
    - app
    - key
    - row
    - tag
    - x
    - y
    - z

# File Header Template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  OpenChatbot
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2,4}\.
                    \/\/

# Custom Reporter (optional)
reporter: "xcode"

# Severity Configuration
warning_threshold: 10
error_threshold: 50 